name: Deploy React App

on:
  push:
    branches:
      - main  # Triggered whenever you push to the main branch
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-python@v4 # Note: Use setup-node for React
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./react_app
        run: npm install

      - name: Build Project
        working-directory: ./react_app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: react_app/dist # Change to 'build' if you are using Create React App (CRA)
          branch: gh-pages # The branch the action will deploy to