import React, { useState, useEffect } from 'react';
import Map from 'react-map-gl/maplibre';
import DeckGL from '@deck.gl/react';
import { ArcLayer } from '@deck.gl/layers';
import 'maplibre-gl/dist/maplibre-gl.css';

// Define the TypeScript interface for our data
interface FlowForecast {
  route: string;
  source_pos: [number, number];
  target_pos: [number, number];
  flow_mw: number;
  limit_mw: number;
  congestion_risk: number;
}

// A free, light-themed basemap from CartoDB (no API key required)
const MAP_STYLE = 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json';

const INITIAL_VIEW_STATE = {
  longitude: 8.5,
  latitude: 46.0,
  zoom: 5.5,
  pitch: 45, // Angled pitch makes the 3D arcs pop
  bearing: 0
};

export default function App() {
  const [data, setData] = useState<FlowForecast[]>([]);

  // Fetch the static JSON generated by our Python/GitHub Action
  useEffect(() => {
    fetch('/forecast.json')
      .then(res => {
        if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
        return res.text(); // read as text first
      })
      .then(text => {
        try {
          const json = JSON.parse(text);
          setData(json);
        } catch(e) {
          console.error("Error parsing JSON:", e, text);
        }
      })
      .catch(err => console.error("Error loading forecast data:", err));
  }, []);

  const layers = [
    new ArcLayer({
      id: 'flow-arcs',
      data,
      // Map the data fields to the layer properties
      getSourcePosition: (d: FlowForecast) => d.source_pos,
      getTargetPosition: (d: FlowForecast) => d.target_pos,
      // Color logic: Red if congestion > 90%, otherwise Green
      getSourceColor: (d: FlowForecast) => d.congestion_risk > 0.9 ? [255, 50, 50] : [50, 200, 50],
      getTargetColor: (d: FlowForecast) => d.congestion_risk > 0.9 ? [255, 50, 50] : [50, 200, 50],
      // Thicker line = higher flow
      getWidth: (d: FlowForecast) => d.flow_mw / 200, 
      pickable: true,
      autoHighlight: true
    })
  ];

  return (
    <div style={{ width: '100vw', height: '100vh', position: 'relative' }}>
      <DeckGL
        initialViewState={INITIAL_VIEW_STATE}
        controller={true}
        layers={layers}
        // deviceProps={{ 
        //   webgl // ensure WebGL2 context
        // }}
        // Native tooltip provided by Deck.gl
        getTooltip={({ object }) => object && (
          `${object.route}\nFlow: ${object.flow_mw} MW\nLimit: ${object.limit_mw} MW\nCongestion: ${(object.congestion_risk * 100).toFixed(1)}%`
        )}
      >
        <Map mapStyle={MAP_STYLE} reuseMaps />
      </DeckGL>
      
      {/* Simple UI Overlay */}
      <div style={{ position: 'absolute', top: 20, left: 20, background: 'white', padding: 20, borderRadius: 8, zIndex: 1, boxShadow: '0 4px 6px rgba(0,0,0,0.1)' }}>
        <h2 style={{ margin: '0 0 10px 0' }}>Grid Flow Explorer</h2>
        <p style={{ margin: 0, color: '#666' }}>24h Horizon Forecast</p>
      </div>
    </div>
  );
}